document.writeln("        <head>");
document.writeln("		<link rel=\"stylesheet\" href=\"../css/study.css\" type=\"text/css\"/>");
document.writeln("		<link rel=\"stylesheet\" href=\"../css/index.css\" type=\"text/css\"/>");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'/>");
document.writeln("		<meta charset=\"utf-8\">");
document.writeln("		<title>班级网站</title>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div class=\"app\">");
document.writeln("			<div class=\"header\">");
document.writeln("				<header>");
document.writeln("					<div class=\"bigtitle\">");
document.writeln("						<h1 id=\"titled\">1</h1>");
document.writeln("						<span id=\"subtitle\">1</span>");
document.writeln("						<span id=\"author\">1</span>");
document.writeln("					</div>");
document.writeln("					<div class=\"menu\">");
document.writeln("						<div class=\"submenu\">");
document.writeln("							<a href=\"../index.html\">回到主页</a>");
document.writeln("						</div>");
document.writeln("						<div class=\"submenu\">");
document.writeln("							<a href=\"../study.html\">回到学习</a>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</header>");
document.writeln("			</div>");
document.writeln("			<div class=\"main\" id=\"container\">");
document.writeln("				");
document.writeln("			</div>");
document.writeln("			<div class=\"footer\">");
document.writeln("				<script type=\"text/javascript\" src=\"../js/footer.js\"></script>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</body>");